# Generated by Django 4.1.3 on 2022-11-17 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(blank=True, max_length=30, null=True)),
                ('tg_id', models.IntegerField()),
                ('school', models.CharField(max_length=30)),
                ('phone_number', models.IntegerField()),
                ('date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
