# Generated by Django 4.1.3 on 2022-11-17 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='surname',
            field=models.CharField(max_length=30),
        ),
    ]
