# Generated by Django 4.1.3 on 2022-11-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0002_alter_registration_surname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Q', models.TextField()),
                ('V1', models.CharField(blank=True, max_length=50, null=True)),
                ('V2', models.CharField(blank=True, max_length=50, null=True)),
                ('V3', models.CharField(blank=True, max_length=50, null=True)),
                ('V4', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
