# Generated by Django 4.1.3 on 2022-11-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0006_rename_surname_result_username_alter_result_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='Answer',
            field=models.BooleanField(blank=True, choices=[('A', models.CharField(blank=True, max_length=50, null=True)), ('B', models.CharField(blank=True, max_length=50, null=True)), ('C', models.CharField(blank=True, max_length=50, null=True)), ('D', models.CharField(blank=True, max_length=50, null=True))], null=True),
        ),
    ]
