# Generated by Django 4.1.3 on 2022-11-22 17:44

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0013_alter_question_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='Answer',
            field=models.CharField(blank=True, choices=[('V1', django.db.models.fields.Field.value_to_string), (models.CharField(blank=True, max_length=50, null=True), 'V2'), (models.CharField(blank=True, max_length=50, null=True), 'V3'), (models.CharField(blank=True, max_length=50, null=True), 'V4')], max_length=50, null=True),
        ),
    ]
