# Generated by Django 4.1.3 on 2022-11-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0019_rename_result_of_test_registration_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='test',
            field=models.IntegerField(blank=True, null=True, verbose_name='Result of test'),
        ),
    ]
