# Generated by Django 3.2.3 on 2022-12-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0024_question_ru_region_ru_result_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='presentation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
