# Generated by Django 3.2.3 on 2022-12-09 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0025_registration_presentation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='username',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='result_ru',
            name='username',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
