# Generated by Django 3.2.3 on 2022-12-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0026_auto_20221209_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='region_ru',
            name='name_lotin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
